name: ot_apps
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.1.0
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: ^3.0.1
  simple_animations: ^1.3.3
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  google_sign_in: ^6.0.1
  iconify_flutter: ^0.0.5
  smooth_page_indicator: ^1.0.1
  cloud_firestore: ^4.4.4
  curved_navigation_bar: ^1.0.3
  firebase_database: ^10.0.16


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/icons/